### ISSUE TITLE
netcdf4 in wxpython can't visualize plot !

### ISSUE THREAD

**Issue by majdo19** [shoyer/h5netcdf#54]
hi, 

i have my app in wxpython , i need to plot some netcdf4 fil in folder 
the problem i have 2 leftpanel the first leftpaneltop  when i select with button choose fil netcdf4 and the second  leftpanelbottom is for visualize the file but when i choose my file they can't open with error : 

Traceback (most recent call last):
  File "/home/sarah/app2.py", line 80, in onOpen
    LeftPanelBottom(parent=self, netCDF4=chosen_file)
TypeError: __init__() got an unexpected keyword argument 'netCDF4'
i work with wxpython4 for python3.6 
[](url)
that my code :

```
import wx
import os
import numpy as np

from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas

from matplotlib.figure import Figure
import matplotlib.pyplot as plt

import netCDF4 
from netCDF4 import Dataset


class MainFrame(wx.Frame):
 
    def __init__(self,parent):
        super().__init__(parent, title="QUICK", size=(2000, 1000))
 
        left = LeftPanel(self)
        middle = MiddlePanel(self)
        right = RightPanel(self)
        sizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer.Add(left, 5, wx.EXPAND)
        sizer.Add(middle, 5, wx.EXPAND)
        sizer.Add(right, 5, wx.EXPAND)
        self.SetSizer(sizer)
        sizer1 = wx.BoxSizer(wx.VERTICAL)
        sizer1.Add(left,2,wx.EXPAND)
        sizer1.Add(right,2,wx.EXPAND)
        sizer1.Add(middle,2,wx.EXPAND)
       
       
        self.Show()

 
class LeftPanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent)
        self.SetBackgroundColour('122')
 
 
class MiddlePanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent)
        self.SetBackgroundColour('179')
 
 
class RightPanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent)
        self.SetBackgroundColour('179 ')
        
class LeftPanelTop(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('snow2')
        List_choices = ["1Km","3Km"]
        List2 = ["3X3","5X5","7X7"]
        self.dateLbl = wx.StaticBox(self, -1, 'Outils ', size=(410, 320))
        
        self.dategraphSizer = wx.StaticBoxSizer(self.dateLbl, wx.VERTICAL)
        combobox1 = wx.ComboBox(self,choices = List_choices, size =(80,20),pos =(180,50))
        combobox2 = wx.ComboBox(self,choices = List2, size =(80,20),pos =(180,90))
        wx.StaticText(self, label='Résolution:', pos=(70, 50))
        wx.StaticText(self, label='Taille de cible:', pos=(70, 90))
        QuickLook = wx.Button(self ,-1, "Open file" , size =(80, 25),pos =(180,130))
        wx.StaticText(self, label='QuickLook:', pos=(70, 130))
        QuickLook.Bind(wx.EVT_BUTTON, self.onOpen)
        self.load_options = "netCDF4 files (nc)|*.nc| Text files (txt) |*.txt| All files |*.*"
        
    def onOpen(self, event): # here for select file netcdf4
        with wx.FileDialog(self, "On open", wildcard=self.load_options,
                           style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST | wx.FD_MULTIPLE) as fileDialog:
            if fileDialog.ShowModal() != wx.ID_CANCEL:
                chosen_file = fileDialog.GetPath()
                if chosen_file.endswith('.txt'):
                    QuickLook(parent=self, text=chosen_file)
                elif chosen_file.endswith('.nc'):
                    LeftPanelBottom(parent=self, netCDF4=chosen_file)
    
        #theproblem is here when i need to visualize the file 
class LeftPanelBottom(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style =  wx.ID_ANY,size=(410,410))
        self.SetBackgroundColour('whitesmoke')
        self.figure = Figure()
        self.axes = self.figure.add_subplot(111)
        self.canvas = FigureCanvas(self, -1, self.figure)
        Quit_button = wx.Button(self, wx.ID_ANY, "&Quit")
        self.sizer = wx.BoxSizer(wx.VERTICAL)
        self.sizer.Add(self.canvas, 1,wx.TOP | wx.LEFT | wx.EXPAND)
        
        #plot figure
    def draw(self):
#selec file 
        fic='S-VISIR_20180220T090000Z.nc'

        path='/net/stockage/2018/02/20/'

        nc = netCDF4.Dataset(path+fic,'r')
        cma_recup=nc.variables['ci_prob30'][:]

        #visualize variable
        plt.pcolormesh(cma_recup)
        plt.colorbar()
        plt.show()       
class LeftPanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
 
        top = LeftPanelTop(self)
        bottom = LeftPanelBottom(self)
 
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(top, 1, wx.EXPAND)
        sizer.Add(bottom, 2, wx.EXPAND)

        self.SetSizer(sizer)
        
class RightPanelTop(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('black')
        canal=wx.Button(self,-1,"Variable",size=(140,30),pos=(100,0))
        dynamique=wx.Button(self,-1,"Dynamique",size=(140,30),pos=(240,0))
        file = wx.Button(self,-1,"File", size = (110,30),pos=(0,0))
        dynamique.SetBackgroundColour('white')
        canal.SetBackgroundColour('white')
        file.SetBackgroundColour('white')
        dynamique.Bind(wx.EVT_BUTTON, self.OnClick)
        file.Bind(wx.EVT_BUTTON, self.onOpen)
        
    def onOpen(self, event):
        wildcard = "netCDF4 files (*.nc)|*.nc| HDF5 files (*.h5) |*.h5"
        dialog = wx.FileDialog(self, "Open netCDF4 Files| HDF5 files", wildcard=wildcard,
                               style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)

        if dialog.ShowModal() == wx.ID_CANCEL:
            return


        path = dialog.GetPath()


        if os.path.exists(path):
            with open(path) as fobj:
                for line in fobj:
                    self.my_text.WriteText(line)

                    
    def OnClick(self,event):
        dlg = wx.TextEntryDialog(self, 'Enter Dynamique of image','Dynamique de image') 
		
        if dlg.ShowModal() == wx.ID_OK: 
         self.text.SetValue("Dynamique:"+dlg.GetValue()) 
        dlg.Destroy()
    
    
        
class RightPanelBottom(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('red')
        
        
class RightPanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent)
 
        top = RightPanelTop(self)
        bottom = RightPanelBottom(self)
 
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(top, 2, wx.EXPAND)
        sizer.Add(bottom, 2, wx.EXPAND)
        self.SetSizer(sizer)
        
class MiddlePanelTop(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('black')
        canal=wx.Button(self,-1,label ="Variable",size=(140,30),pos=(100,0))
        dynamique=wx.Button(self,-1,"Dynamique",size=(140,30),pos=(240,0))
        file = wx.Button(self,-1,"File", size = (110,30),pos=(0,0))
        dynamique.SetBackgroundColour('white')
        
        canal.SetBackgroundColour('white')
        file.SetBackgroundColour('white')
        dynamique.Bind(wx.EVT_BUTTON, self.OnClick)
        file.Bind(wx.EVT_BUTTON, self.onOpen)
        
    def onOpen(self, event):
        wildcard = "netCDF4 files (*.nc)|*.nc"
        dialog = wx.FileDialog(self, "Open netCDF4 Files", wildcard=wildcard,
                               style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)

        if dialog.ShowModal() == wx.ID_CANCEL:
            return


        path = dialog.GetPath()

        if os.path.exists(path):
            with open(path) as fobj:
                for line in fobj:
                    self.my_text.WriteText(line)
        
    def OnClick(self,event):
        dlg = wx.TextEntryDialog(self, 'Enter Dynamique of image','Dynamique de image') 
		
        if dlg.ShowModal() == wx.ID_OK: 
         self.text.SetValue("Dynamique:"+dlg.GetValue()) 
        dlg.Destroy()
         
        
class MiddlePanelBottom(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('black')
        canal=wx.Button(self,-1,"Variable",size=(140,30),pos=(100,0))
        dynamique=wx.Button(self,-1,"Dynamique",size=(140,30),pos=(240,0))
        file = wx.Button(self,-1,"File", size = (110,30),pos=(0,0))
        dynamique.SetBackgroundColour('white')
        canal.SetBackgroundColour('white')
        file.SetBackgroundColour('white')
        dynamique.Bind(wx.EVT_BUTTON, self.OnClick)
        file.Bind(wx.EVT_BUTTON, self.onOpen)
        self.load_options = "netCDF4 files (nc)|*.nc| Text files (txt) |*.txt| All files |*.*"

        
    def onOpen(self, event):
        wildcard = "netCDF4 files (*.nc)|*.nc"
        dialog = wx.FileDialog(self, "Open netCDF4 Files", wildcard=wildcard,
                               style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)

        if dialog.ShowModal() == wx.ID_CANCEL:
            return


        path = dialog.GetPath()

        if os.path.exists(path):
            with open(path) as fobj:
                for line in fobj:
                    self.my_text.WriteText(line)
        
    def OnClick(self,event):
        dlg = wx.TextEntryDialog(self, 'Enter Dynamique of image','Dynamique de image') 
		
        if dlg.ShowModal() == wx.ID_OK: 
         self.text.SetValue("Dynamique:"+dlg.GetValue()) 
        dlg.Destroy()
        
        
class MiddlePanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent)
 
        top = MiddlePanelTop(self)
        bottom = MiddlePanelBottom(self)
 
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(top, 3, wx.EXPAND)
        sizer.Add(bottom, 3, wx.EXPAND)
        self.SetSizer(sizer)
        

        
class PanelTop(wx.Panel):
    def __init__(self,parent):
        super().__init__(parent)
        self.SetBackgroundColour('black')
class PanelBottom(wx.Panel):
    def __init__(self,parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('grey77')
        self.dateLbl = wx.StaticBox(self, -1, 'Info', size=(700, 280))
        self.dategraphSizer = wx.StaticBoxSizer(self.dateLbl, wx.VERTICAL)

class RightPanelBottom(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent)
        
        top = PanelTop(self)
        bottom = PanelBottom(self)
        sizer1 = wx.BoxSizer(wx.VERTICAL)
        sizer1.Add(top,2, wx.EXPAND)
        sizer1.Add(bottom,4,wx.EXPAND)
        self.SetSizer(sizer1)

class leftPanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('black')
class midllePanel(wx.Panel):
     def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('black')
        
class rightPanel(wx.Panel):
    def __init__(self, parent):
        super().__init__(parent,style = wx.SUNKEN_BORDER)
        self.SetBackgroundColour('black')


    
      
class PanelTop(wx.Panel):
    def __init__(self,parent):
        super().__init__(parent)
        left = leftPanel(self)
        right = rightPanel(self)
        midlle = midllePanel(self)
        sizer1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer1.Add(left,2, wx.EXPAND)
        sizer1.Add(midlle,2,wx.EXPAND)
        sizer1.Add(right,2,wx.EXPAND)
        self.SetSizer(sizer1)


        
app = wx.App()
frame = MainFrame(None).Show()
app.MainLoop()
```

thanks for help

**Comment by jhamman** [comment]
I think you have posted in wrong repo. I suggest posting questions like this on stack overflow. Or perhaps on the WX repo.

**Comment by majdo19** [comment]
> I think you have posted in wrong repo. I suggest posting questions like this on stack overflow. Or perhaps on the WX repo.

i posted it in stack overflow but i don't have any answers ...
